"""Prepare for tasks and services

Revision ID: bc7b248e78c1
Revises: 13a36d65cdb3
Create Date: 2020-10-19 16:16:11.442254

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bc7b248e78c1"
down_revision = "13a36d65cdb3"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("due", sa.DateTime(), nullable=False),
        sa.Column("assigned_on", sa.DateTime(), nullable=False),
        sa.Column("service_name", sa.String(), nullable=False),
        sa.Column("full_text", sa.String(), nullable=True),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(("user_id",), ("users.id",)),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "users",
        sa.Column(
            "services_data", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "services_data")
    op.drop_table("tasks")
    # ### end Alembic commands ###
